version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: 'always'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - task-manager-data/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=PizzadeCupimAoAlho23#G4P
      - POSTGRES_DB=task-manager 
      - POSTGRES_USER=root
